# fly.toml app configuration file generated for controltaxisapp on 2026-07-05T11:37:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'controltaxisapp'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[[mounts]]
  source = 'data_volume'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  # CAMBIO: Establecemos el tiempo de espera antes de que se apague
  # Si nadie entra en 15 minutos, se apaga.
  auto_stop_machines = 'stop'
  auto_start_machines = true
  # CAMBIO: Mantenemos al menos 1 máquina encendida para que responda al instante
  min_machines_running = 0
  processes = ['app']

[vm]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
