// <auto-generated />
using System;
using ControlTaxisApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlTaxisApp.Migrations
{
    [DbContext(typeof(ControlTaxisContext))]
    partial class ControlTaxisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ControlTaxisApp.Models.Conductor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conductores", (string)null);
                });

            modelBuilder.Entity("ControlTaxisApp.Models.Festivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Festivos");
                });

            modelBuilder.Entity("ControlTaxisApp.Models.LiquidacionDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Ahorro")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConductorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Gastos")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PicoYPlaca")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Producido")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConductorId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("LiquidacionesDiarias", (string)null);
                });

            modelBuilder.Entity("ControlTaxisApp.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Garantia")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Iva")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Kilometraje")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProximoCambio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Taller")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMantenimientoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoMantenimientoId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("ControlTaxisApp.Models.TipoMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposMantenimiento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Motor"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Caja de Cambios"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Frenos"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Suspensión"
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Sistema Eléctrico"
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Llantas"
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Cambio de Aceite"
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Aire Acondicionado"
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Otro"
                        });
                });

            modelBuilder.Entity("ControlTaxisApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ControlTaxisApp.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vehiculos", (string)null);
                });

            modelBuilder.Entity("ControlTaxisApp.Models.LiquidacionDiaria", b =>
                {
                    b.HasOne("ControlTaxisApp.Models.Conductor", "Conductor")
                        .WithMany()
                        .HasForeignKey("ConductorId");

                    b.HasOne("ControlTaxisApp.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conductor");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("ControlTaxisApp.Models.Mantenimiento", b =>
                {
                    b.HasOne("ControlTaxisApp.Models.TipoMantenimiento", "TipoMantenimiento")
                        .WithMany()
                        .HasForeignKey("TipoMantenimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlTaxisApp.Models.Vehiculo", "IdVehiculoNavigation")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdVehiculoNavigation");

                    b.Navigation("TipoMantenimiento");
                });
#pragma warning restore 612, 618
        }
    }
}
